### PR TITLE
D1b manipulate -> operate

### PR DESCRIPTION
**Pull request by Laura-O**
As mentioned in #511, we should change all occurrences of "manipulate" to "operate".

### CODE REVIEW

**Review by Claster — APPROVED** [review]

**Comment by viroulep** [comment]
There is one occurrence still in A3c3+, should this one be changed too?

**Comment by Laura-O** [comment]
> There is one occurrence still in A3c3+, should this one be changed too?

Oops... I forgot to check the guidelines. :(

**Review by viroulep — APPROVED** [review]

**Comment by viroulep** [comment]
Looks good now!

**Comment by lgarron** [comment]
I didn't catch this before merging, but thanks for sending it!

**Pull request merged**
