### PR TITLE
2i) Clarify that interaction with the Stackmat timer is allowed, even though it is electronic.

### PR DESCRIPTION
**Pull request by lgarron**
This came up in #567.

### CODE REVIEW

**Comment by sam596** [comment]
Should this also include the stopwatch for longer attempts? For instance, I assume I'm allowed to pick up the stopwatch during a MBLD attempt to see my time if I can't see it from my position.

**Comment by lgarron** [comment]
@viroulep Ping. :-)

**Comment by viroulep** [comment]
Shouldn't we add something about the stopwatch?
It should be fine to let competitors touch/move it to better see it.

**Comment by lgarron** [comment]
> Shouldn't we add something about the stopwatch?
> It should be fine to let competitors touch/move it to better see it.

We're still discussing that in #581.

**Comment by lgarron** [comment]
Unless you were referring to the FMC stopwatch, which it appears I do need to take into account:

https://www.worldcubeassociation.org/regulations/#E3d

**Comment by viroulep** [comment]
To clarify: I was referring to the stopwatch used for attempts longer than 10 minutes (such as during mbf or big blinds).

**Comment by lgarron** [comment]
I'm going to merge this now, and bump the priority of the stopwatch discussion in #581.

**Pull request merged**
