### PR TITLE
Remove inconsistent quotation marks

### PR DESCRIPTION
**Pull request by Nanush7**
Removed quotation marks in DNF from 5b5++ and 5b5++++.

Reported by @c-goodyear.

### CODE REVIEW

**Comment by Nanush7** [comment]
Merging directly to official as it is a small fix.

**Review by Nevseros — APPROVED** [review]
Nothing significant so LGTM!

**Review by Ivan-Brigidano — APPROVED** [review]

**Review by Ivan-Brigidano — DISMISSED** [review]
I believe the PR should be to merge it into `draft` and not `official`.

**Comment by Nanush7** [comment]
> I believe the PR should be to merge it into `draft` and not `official`.

I did it directly to `official` because it is a small correction. Isn't this the common procedure for small fixes?

**Comment by Ivan-Brigidano** [comment]
I believe it's cleaner to merge it into `draft`, and then `draft` into `official`.
@lgarron can you please confirm that?

**Comment by lgarron** [comment]
> I believe it's cleaner to merge it into `draft`, and then `draft` into `official`.
> @lgarron can you please confirm that?

Agreed, this should definitely go to `draft`, not `official`.

This is also a very minor change that doesn't affect interpretation, which I don't think warrants asking the Board for an official update.

**Comment by Nanush7** [comment]
Changed to `draft`

**Review by lgarron — APPROVED** [review]

**Pull request merged**
