### PR TITLE
Remove MBLD cutoff

### PR DESCRIPTION
**Pull request by Rouxles**

### CODE REVIEW

**Comment by Rouxles** [comment]
See #1057 for the same thing but for FMC.

**Review by JoaoViniciusSantos — APPROVED** [review]

**Comment by Rouxles** [comment]
image
MBLD Cutoff Stats

**Review by lgarron — APPROVED** [review]
LGTM for the wording changes as well.

**Comment by Rouxles** [comment]
Not implementing because WCA staff believes that it is useful to keep.

**Pull request closed without merging**
