### PR TITLE
Fix #411

### LINKED ISSUE #411: Switch to American spelling
(Sorry if there is already an issue for this, I couldn't find one.)

Ron told me that since we're going to incorporate as a NPO in the US, we are going to go with American spelling on the website and in the Regulations.

(Related: @pedrosino recently went to the effort of changing all occurrences of "organisation" to "organization" on the WCA website. See https://github.com/thewca/worldcubeassociation.org/pull/1119#issuecomment-274271742.)

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
Ok, I think I did it the right way now. I changed "organisation" to "organization" in order to fix #411.

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
I changed the Guidelines too.

**Comment by jfly** [comment]
Just checking, is the only British vs American English issue in our regulations related to the spelling of the word "organization"? You could imagine that there are other things... Color vs colour for instance.

**Comment by AlbertoPdRF** [comment]
I'll check carefully tomorrow if there are more issues like the one you
pointed out, thanks!


El 19 mar. 2017 1:18, "Jeremy Fleischman" <notifications@github.com>
escribió:

Just checking, is the only British vs American English issue in our
regulations related to the spelling of the word "organization"? You could
imagine that there are other things... Color vs colour for instance.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thewca/wca-regulations/pull/416#issuecomment-287584815>,
or mute the thread

**Comment by AlbertoPdRF** [comment]
I changed "colour" to "color" (and derivatives).

Also, I corrected other issues like:
- Centre -> Center (only 1 "centre", in guidelines)
- Recognise -> Recognize
- Anti(-clockwise) -> Counter(-clockwise)
- Fulfil -> Fulfill (only 1 "fulfil", in regulations)
- Authorise -> Authorize (only 1 "(un-)authorise(-d), in regulations)

Let me know if I missed something more, and I'll change it too :)

**Comment by Laura-O** [comment]
I found some more:

Guidelines:
* recognisable -> recognizable
* honours -> honors

Regulations:
* labelled -> labeled
* metres -> meters

Let's wait for some feedback from @lgarron. He had some more small fixes, so maybe we can combine all these fixes and update the website.

**Comment by lgarron** [comment]
I think all my trivial fixes are visible at https://github.com/thewca/wca-regulations/pulls

**Pull request merged**
