### PR TITLE
Add Portuguese translation for May 21, 2013

### PR DESCRIPTION
**Pull request by timhabermaas**

### CODE REVIEW

**Comment by lgarron** [comment]
Note that there were _two_ May releases this year: https://github.com/cubing/wca-documents/releases

**Comment by lgarron** [comment]
Also, feel free to work in a branch in cubing/wca-documents. I use it as my origin, because there's likely to be little conflict if we use branches properly. And everything except `cubing/wca-documents/official` doesn't really matter.

**Comment by timhabermaas** [comment]
> Note that there were two May releases this year

Oh, didn't know this. I'll change the commit message.

> Also, feel free to work in a branch in cubing/wca-documents.

Alright.

**Comment by timhabermaas** [comment]
@lgarron The pdf generation blows up with:

> Overfull \hbox (4.76506pt too wide) in paragraph at lines 2058--2061
> []\OT1/cmr/m/n/12 3a+) [ES-CLAREC-I-MENTO] Com-peti-dores po-dem usar quebra-ca
> be^^Xcas em qual-quer tamanho
> [23] [24] [25] [26] [27] (build/regulamento-e-orientacoes-wca-2013.aux
> ! Missing \endcsname inserted.
> <to be read again> 
>                    \unhbox 
> l.34 ...C {~a}o}{{}{1}{Tradução}{section*.3}{}}
> 
> !  ==> Fatal error occurred, no output PDF file produced!
> Transcript written on build/regulamento-e-orientacoes-wca-2013.log.

How did you find the invisible characters in https://github.com/cubing/wca-documents/commit/4c71d12?

**Comment by lgarron** [comment]
I tried to decode the LaTeX warning. Almost every language requires fixing something that would never be a concern in an ideal world.

Lemme take a look at this.

**Comment by lgarron** [comment]
HTML and PDF build fine for me, and I don't have any great ideas. :-(

**Comment by timhabermaas** [comment]
Yeah, I just went back to master and tried `./make.py -w` and got another error for a different language. :(

**Comment by timhabermaas** [comment]
Since it works for you, I'm gonna merge it.

**Pull request merged**
