### PR TITLE
Clarify borrowing puzzles

### LINKED ISSUE #390: 3a+++ wording
Pedantic/pointless change but anyway:

3a+++) CLARIFICATION Competitors may borrow puzzles from other competitors privately, to use in competition.

A competitor is also allowed to borrow puzzles from others who are not competing, right?

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #390

### CODE REVIEW

**Comment by lgarron** [comment]
On reflection, I think it would be good to be explicit. How about "others (including other competitors in the same round)"

**Comment by pedrosino** [comment]
I'm fine with that as well. Will wait for someone else to comment

**Comment by Laura-O** [comment]
Yep, I think Lucas' recommendation is better. Can you change your PR please @pedrosino ?

**Comment by pedrosino** [comment]
Ok, done.

**Pull request merged**
