### PR TITLE
Clerical Fixes

### PR DESCRIPTION
**Pull request by Rouxles**

### CODE REVIEW

**Review by hanwu85 — APPROVED** [review]
LGTM!

**Comment by hanwu85** [comment]
There is one link need to be updated as well
 `WCA List of Recognized Regions` in 2e1

**Review by Nanush7 — CHANGES_REQUESTED** [review]
The link in 2e1 is also broken. Please wait before merging.

**Review by Nanush7 — APPROVED** [review]

**Comment by Nanush7** [comment]
Just in case, the link in 2e1 [does not require any changes](https://github.com/thewca/worldcubeassociation.org/pull/8942/files#diff-f6ce3d9abfbed116ed786ce0aeaac8d4e49b2b041275415259124afe0b85c25f), it should work again soon.

**Pull request merged**
