### PR TITLE
Add Belarusian translation

### PR DESCRIPTION
**Pull request by timhabermaas**
The information Roman Ostapenko provided:
1. Latest commit - 06e4f31b76
2. Translators: Anatolii Kalinin (2011KALI01; http://vk.com/id18221009), Ilya Tereshko (2012TERE01; http://vk.com/id37072463)
3. Translation of:
   a) The native name of your translation language, in that language: "Беларуская мова"
   b) Regulations: "Палажэнні [WCA 2013]"
   c) Guidelines: "Дапаўненні да Палажэнняў [WCA 2013]"
   d) I think that "wca-regulations-and-guidelines-2013.pdf" will be more understandable than its transliteration .
## TODO
- [x] revert translated `<article-1>` tags
- [x] integrate with wca-documents-extra

### CODE REVIEW

**Comment by lgarron** [comment]
What's the status on this?

---

Note: Considering that `wca-documents-extra` is annoying to keep in sync, a useful idea would be to store the data in the translated repo. I've considered doing it, except:
- I haven't tried to ask for push control over all repos with canonical language versions (I want to _encourage_ federation), so pushing the format change would be annoying.
- It commits us to a particular format.

But perhaps the benefits would outweigh this. Feel free to think about it... or not. :-P

**Comment by timhabermaas** [comment]
I haven't changed anything in `wca-documents-extra`, yet. I simply didn't have time. I'll take a look at in on Wednesday and maybe I'll figure out a way to keep the two branches in sync without the drawbacks you listed. :)

**Comment by timhabermaas** [comment]
@lgarron I finally finished working on it. Could you take a look at https://github.com/cubing/wca-documents-extra/pull/43 and this PR? Everything worked fine locally.

**Comment by lgarron** [comment]
I had to remove two invisible characters to get LaTeX to accept it: 4c71d12

**Pull request merged**
