### PR TITLE
Tweaked language to allow for multiple official versions of the scrambling software.

### PR DESCRIPTION
**Pull request by jfly**
Continuation of #396.

### CODE REVIEW

**Comment by jfly** [comment]
Turns out there are a few more occurrences of the phrase "scramble program" that needed updating.

**Comment by lgarron** [comment]
I've reverted the `draft` branch so we can get this right.
Would you mind splitting the URL changes from the scrambler changes, though?

**Comment by lgarron** [comment]
> I've reverted the draft branch so we can get this right.
> Would you mind splitting the URL changes from the scrambler changes, though?

Ah, I pushed the wrong revert. I think we can merge this now.

**Comment by jfly** [comment]
Would you like me to squash the commits a bit? There are 4 commits in here, I think it should be 1.

edit: nevermind, I just did it.

**Comment by AlbertoPdRF** [comment]
LGTM!

**Pull request merged**
