### PR TITLE
Result instead of attempt time for time limit

### PR DESCRIPTION
**Pull request by cubizh**
In the "attempt" definition, I think that "results" is a better fit here and for the continuation of the next sentence.

### CODE REVIEW

**Comment by Laura-O** [comment]
Can you explain that a bit more, @cubizh?
I think _attempt_ fits quite well here and it's also used in A1a).

**Comment by cubizh** [comment]
Of course.
I think A1a) is on the fence too, but it is more noticable on A1a2) with my interpretation.
It all boils down to what an "attempt" is, as defined by the regulations.
An attempt is defined by regulation A3b2) (how it starts) and by regulation A7c) (how it ends). 
In practice, we don't use A1a)/A1a2) with the time that the attempt takes (with inspection time added and signing the solve) but really only use the actual solve time or the "result" (what appears on the timer) for time limits. At least I think that's the spirit of this regulation. I feel that A1a2) should refer to the same "solve time" as A1a1). That's why I am not much of a fan, for consistency, of having the word "attempt" there, but I welcome the opinion of others. :)

**Comment by Laura-O** [comment]
Thank you, I got your point now and I completely agree to your explanation.
That's also consistent with how _attempt_ and _result_ is used in 9f) and other articles.

**Comment by lgarron** [comment]
I don't think it makes sense to change this without A1a).

I think we should change everything under A1a) to say "solve" or "attempt", and I personally think it's most natural to say that the attempt has a time limit (which is enforced based on the final result based from the solve).

**Comment by Laura-O** [comment]
What about "results of 3 attempts..."?
This emphasizes that it's not a time limit for the whole attempt (from A3 to A7c, as @cubizh explained) and also connects the first and second sentence.

P.S.: sorry for merging this a bit too hasty. :-)

**Comment by cubizh** [comment]
I agree A1a) could be rephrased but I don't think A1a) is that much wrong, because by setting a time limit to the solve, you are already (sort of) establishing a time limit to the attempt, because of the 1 minute pre-inspection + 15s inspection + solve time. The only gray area is the signing part that is untimed. But if that last part is neglected, the attempt has a time limit if a limit is set on the solve. Some people may misinterpret timing the attempt and timing the solve, unless there's somewhere explicitly said that the time of an attempt is measured by the solve time only.

**Comment by lgarron** [comment]
Is A1a5 not clear enough?
(It currently still says "solve", although I think "attempt" would be better.)

**Comment by cubizh** [comment]
I agree with changing A1a5) to "attempt" instead of "solve", but it still is unclear that the time of the attempt is supposed to be the time of the solve for A1a2) purposes (or others where it applies). Perhaps an [addition] guideline?

**Pull request merged**
