### PR TITLE
Solve-someone-elses-scramble.md

### PR DESCRIPTION
**Pull request by avgalen**
Prevent cheating by scrambling for yourself or by judging a cube that you scrambled for a friend

### CODE REVIEW

**Comment by Claster** [comment]
A scrambler can't solve a puzzle scrambled by himself by 1h1. As for judging: sometimes at the beginning of a new group or event, things can be sped up if several judges also scramble puzzles for their competitors. If someone wants to cheat, he can do it while being only a judge ([example](https://www.worldcubeassociation.org/forum/viewtopic.php?f=9&t=1067)). Solution is using only trustworthy judges.

**Comment by avgalen** [comment]
Thank you for pointing me at 1h1. I had to read it a few times to see if it would really cover all abuse but you are right: It covers all abuse for a scrambler to scramble for himself.

For judging your example is well taken and your solution is (of course) the only real solution. I also recognize the (unfortunate) situation that judges help with scrambling at the beginning of a new group but NOT that they scramble for their own competitor. In that situation they should scramble a few puzzles and then pick up a random puzzle that was (probably) scrambled by somebody else. This is the reason I put purposefully in the rule.

**Comment by Laura-O** [comment]
How can you judge if this was done by purpose (and therefore a
disqualification from the competition is appropriate)?
Furthermore: why do we need this regulation? Is this really a problem in
competitions? Is this something we can not manage with the existing
regulations (e.g. 2k)?

2014-05-21 16:20 GMT+02:00 avgalen notifications@github.com:

**Comment by avgalen** [comment]
"Scramblers scramble, judges judge, and never the two shall meet"
If a judge brings a cube to the scrambling table, scrambles it and walks away I don't trust it.
If a scrambler scrambles 20 cubes, finishes scrambling and helps with judging at the end of the group he MIGHT pick up one of the cubes that he scrambled but I would trust that.
The whole point is that I don't trust little boy X that scrambles for his friend Y and also judges him. Apparently this is happening: (source http://www.speedsolving.com/forum/showthread.php?47691-Multiple-judges-per-average) Originally Posted by hcfong  View Post
...One person would pretty much claim to cube of his or her friend and hold on to it and both scramble and judge the solves...
And yes, this pretty much falls under https://www.worldcubeassociation.org/regulations/#2k2 so both my concerns are already covered under the current regulations and I withdraw my pull request (how do I do that in github? just "Close & Comment"?

**Comment by lgarron** [comment]
Yeah, `Close & Comment` should work. But I'd like to leave it open for now. I think we could use a guideline that encourages accountable behaviour.

**Comment by lgarron** [comment]
Closing in favor of https://github.com/cubing/wca-documents/issues/121#issuecomment-64724071.

**Pull request closed without merging**
