### PR TITLE
Remove cutoff for FMC

### PR DESCRIPTION
**Pull request by Rouxles**

### CODE REVIEW

**Comment by Rouxles** [comment]
See #1058 for the same thing but for MBLD (they are in separate PRs because in general we feel differently about FMC and MBLD cutoffs)

**Review by CelineTrammi — APPROVED** [review]

**Comment by Rouxles** [comment]
image
FMC Cutoff Stats

**Review by lgarron — APPROVED** [review]
LGTM in terms of wording changes; thanks for posting the history, @Rouxles!

**Comment by Rouxles** [comment]
Not implementing because WCA staff believes that it is useful to keep.

**Pull request closed without merging**
