### PR TITLE
Activate Travis 

### PR DESCRIPTION
**Pull request by viroulep**
I activated Travis for the repository, so lets try the travis file :)

### CODE REVIEW

**Comment by jfly** [comment]
LGTM!

**Comment by lgarron** [comment]
Sounds cool. How is the `pip` module maintained?

**Comment by viroulep** [comment]
So right now it's just [me](https://github.com/viroulep/wca-regulations-compiler/blob/master/setup.py), but I guess we could easily have a shared access for cubing or something.
Do you already have a suggestion in mind?

**Comment by lgarron** [comment]
If we're going to start using it as part of our process, I think we should move the repo to `/cubing` and add the appropriate team ACLs. I think it's fine for you to be the listed PIP maintainer, although we should make sure there is a bus factor greater than 1.

**Comment by viroulep** [comment]
That's fine by me, I'll request the ownership transfer to cubing.
Also if anyone from the wrc/software team volunteers and has a Pypi account I can add him as a package maintainer!

**Comment by lgarron** [comment]
I have one; what do info do you need? My username on PyPi is `lgarron`.

**Comment by viroulep** [comment]
Nothing more, I just added you :)
I thought I could ask for transfer even if not being an owner of cubing but apparently I can't, could you create an empty "wca-regulations-compiler" on cubing please?

**Comment by lgarron** [comment]
> could you create an empty "wca-regulations-compiler" on cubing please?

Done.

**Comment by viroulep** [comment]
Thanks, I've updated the various info.

**Pull request merged**
