### PR TITLE
Migrate Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by gregorbg**

### CODE REVIEW

**Review by Ivan-Brigidano — APPROVED** [review]
Is the WST able to merge it if we approve it? If not, please let us know when it's ready so that we can merge it (same goes for `wca-regulations-translations`).

**Comment by gregorbg** [comment]
Interestingly enough, I am not able to merge this despite being WST. It says "can be merged by project collaborators", which I assume refers to WRC. Please go ahead and merge this PR at your convenience.

**Comment by gregorbg** [comment]
(same goes for `wca-regulations-translations`) :wink:

**Comment by Ivan-Brigidano** [comment]
Travis is not allowing me to merge this PR: "Some checks haven’t completed yet".

**Comment by Ivan-Brigidano** [comment]
@gregorbg what can we do from the WRC to merge this PR?

**Comment by gregorbg** [comment]
For some reason, GitHub is still trying to run Travis despite me deliberately deleting the Travis config in this PR
I will try to forcefully disable the Travis check since it is now outdated.

**Pull request merged**
