### PR TITLE
Add a missing dot at 9b5

### PR DESCRIPTION
**Pull request by Ivan-Brigidano**

### CODE REVIEW

**Comment by Ivan-Brigidano** [comment]
I have also corrected the small error at `12a2` by @denthebro at #948

**Review by lgarron — APPROVED** [review]

**Comment by mintydev789** [comment]
I am new to this, so how long does it usually take to see the changes on the website?

**Comment by Ivan-Brigidano** [comment]
> I am new to this, so how long does it usually take to see the changes on the website?

This can't be merged to current Regulations per [Motion 14.2019.1](https://www.worldcubeassociation.org/documents/motions/14.2019.1%20-%20Amendments%20of%20Regulations.pdf). So the changes will take into effect with the next update of the Regulations, presumably on January 1, 2021

**Comment by mintydev789** [comment]
Oh, that is unfortunate

**Pull request merged**
