### PR TITLE
Make puzzle related announcement not strictly mandatory

### PR DESCRIPTION
**Pull request by hanwu85**
Making SQ-1 inserts and clock stands announcement not mandatory.

[Discussion on the WCA forum](https://forum.worldcubeassociation.org/t/modify-a2b1-and-f2a-to-not-require-an-announcement/1291)

### CODE REVIEW

**Comment by xsrvmy** [comment]
Is there a particular reason that it is being changed to a "may" instead of a "should"?

**Comment by hanwu85** [comment]
Hi,

This is  open for discussion, currently this is only a draft.
What do you think of MAY vs. SHOULD in this situation?

**Comment by Ivan-Brigidano** [comment]
I think it's better to use "should" so that the announcement still needs to be done but it's not strictly mandatory.

**Comment by hanwu85** [comment]
I have changed the MAYs to SHOULDs. Thanks!

**Review by Ivan-Brigidano — APPROVED** [review]

**Pull request merged**
