### PR TITLE
Added the new timer generation

### PR DESCRIPTION
**Pull request by Laura-O**

### CODE REVIEW

**Comment by viroulep** [comment]
Looks good !

**Comment by Claster** [comment]
Sorry for looking at it only now, after it was merged.

Don't you actually confuse two different timers? There is gen 3 timer (without data port IIRC) which is not allowed at the comps currently, and there is pro timer which is allowed. Is it a good idea to write "Generation 3 Pro Timer"?

**Comment by viroulep** [comment]
I wondered about this too and found out that Speedstacks also refers to the pro timer using "Gen 3 pro timer" (see [here](https://www.speedstacks.com/store/retail/speed-stacks-stackmat-pro-timer/), the note line).

**Comment by Laura-O** [comment]
Yes, I had also asked Speed Stacks about the proper naming of the timer generations and they confirmed that.

There is also an issue about the difference between Generation 3 and Pro Timers here: #227 
As obviously nobody was using them back then and they are not available anymore, I think it's correct to use the currently used naming in the regulations.

**Comment by lgarron** [comment]
> I wondered about this too and found out that Speedstacks also refers to the pro timer using "Gen 3 pro timer" (see here, the note line).

Hmm, it seems you're right. Also here: https://www.speedstacks.com/store/retail/speed-stacks-stackmat-pro/

I wish they were more clear about this. I think the change we have now is accurate enough, but I'm worried it will cause confusion about whether "non-Pro" Generation 3 timers are now allowed. Not everyone is likely to know the distinction. Maybe we should have a page which lists permitted timer equipment, too. :-/

**Comment by Claster** [comment]
Or maybe add a clarification to guidelines: "Gen 3 timers which are not pro are not allowed"?

**Comment by TimMcMahon** [comment]
Should particular batches of Speed Stacks timers be reviewed and added to a list of approved timers?

Speed Stacks might modify the Gen 4 Pro Timer over the next 12 months if they identify issues with earlier batches.

**Comment by Laura-O** [comment]
What would be the aim of that?

Those "batches" are released without an announcement. When the battery compartment of the Gen3 timers was updated, online shops sold the old versions even a year later...
It would make things really complicated to differentiate between these batches.

I agree that it would be good to make a list of approved equipment, but breaking this down to the updates of timer generations seems to be more confusing than helpful.

**Pull request merged**
