### PR TITLE
fix inconsistent link

### PR DESCRIPTION
**Pull request by oyyq99999**

### CODE REVIEW

**Review by mirandapedro — APPROVED** [review]
LGTM.

**Review by Ivan-Brigidano — APPROVED** [review]
LGTM and thanks your for spotting it. What a shame not to have noticed a few days before!

**Comment by Ivan-Brigidano** [comment]
I just noticed that this PR was for `official` and not for `draft`. @lgarron should we revert this changes (and how) and only merge them into `draft` to avoid future conflicts?

_I'm copying my text from Slack to keep a public record._

**Comment by lgarron** [comment]
> I just noticed that this PR was for `official` and not for `draft`. @lgarron should we revert this changes (and how) and only merge them into `draft` to avoid future conflicts?

Yeah, let's try to keep things proper and run it by the Board. Let's revert this on `official` and then do it properly.

**Comment by oyyq99999** [comment]
It should be fine to pull it to draft now to avoid future conflicts. But if that's strict rules of the repo, it's ok to revert too.

**Comment by mirandapedro** [comment]
If the WRC agrees, I'll go ahead and ask the Board to approve this update with the procedure of correction of clerical errors described in section 3 of the [14.2019.1 WCA motion](https://www.worldcubeassociation.org/documents/motions/14.2019.1%20-%20Amendments%20of%20Regulations.pdf).

**Comment by Epride** [comment]
The Board approves this change

**Comment by Ivan-Brigidano** [comment]
Thanks for the information, Ethan! I'll create a PR for replicating the changes in `draft`.

**Pull request merged**
