### PR TITLE
Recognize Mean of 3 for 4x4x4/5x5x5 BLD. Closes #539.

### LINKED ISSUE #539: Officially Recognizing 4x4 BLD and 5x5 BLD Mean Of 3 Results
I would like to propose that 4x4 Blindfolded and 5x5 Blindfolded mean of 3s  be an officially recognized ranking for WCA. Achieving such a result is a huge accomplishment that often goes under the radar since WCA does not recognize these results.

# Pros
- Blindfolded events is a constant battle between someone's accuracy and speed. We already award results based on accuracy on a single result, and recognizing means will award an even bigger difficulty of accuracy.
- Gives competitors an additional goal to strive for in their official results.
- These means are already unofficially recognized on WCA as "Missing Averages". They would no longer be missing if they were officially recognized.
- Adds consistency to our results since 3x3 Blindfolded already has mean of 3 recognized officially.

# Cons
- Not many competitors have 4x4 BLD and 5x5 BLD means.
- The "all events Club" becomes an even rarer achievement (also seen as a Pro).
- Competitors will start "safety solves" in order to complete a mean.
- Not all competitions hold 4x4 BLD and 5x5 BLD in the bo3 format, so many competitors will not have an opportunity to accomplish these.

# Community
As seen on a recent [Speedsolving thread.](https://www.speedsolving.com/forum/threads/should-4bld-and-5bld-means-be-recognized-officially.67187/) 48/57 (84.2%) voted to officially recognize these means. I would also like to see a delegate vote on this issue.

# Statistics / Counterarguments to Cons
- There are currently 63 competitors with 4x4 Blindfolded means, with 103 mo3 results total and 20 competitors with 5x5 Blindfolded means, with 23 mo3 results 
- There is already another level of "all events Club" which includes having 4x4 Blindfolded and 5x5 Blindfolded Means.
- Many competitors are already safetying solves in order to complete a mean. ([see Mark Boyanowski's 5x5 Blindfolded mean](https://www.worldcubeassociation.org/persons/2014BOYA01?event=555bf)) 
- Out of all competitions holding 4x4 BLD or 5x5 BLD here is the format that they were held in:

|eventId | formatId | rounds 
| -------- | -------- | -------- |
|444bf | 1 | 65
|444bf | 2 | 232
|444bf | 3 | 804
|555bf | 1 | 67 
|555bf | 2 | 142 
|555bf | 3| 601 

And from 2017 Only:

|eventId | formatId | rounds 
| -------- | -------- | -------- | 
|444bf | 1 | 2 
|444bf | 2 | 12 
|444bf | 3 | 208 
|555bf | 1 | 6 
|555bf | 2 | 5 
|555bf | 3 | 168 

Relevant Query:
```sql
Select eventId, formatId, COUNT(*) as rounds FROM
(
    SELECT * FROM Results Where eventId = '444bf' OR eventId = '555bf'
    Group BY CompetitionId, RoundTypeId, eventId
) a
GROUP BY eventId, formatId
```

### PR DESCRIPTION
**Pull request by lgarron**
See #539 for discussion.

### CODE REVIEW

**Comment by olfrost** [comment]
Updates?

**Comment by lgarron** [comment]
@Claster, @kingmathyall, are you still in favor?

**Comment by Claster** [comment]
Well, I am :)

**Comment by kingmathyall** [comment]
I'm really torn between the two as I can't help but take into account that most peoples' "silver/gold/platinum" member statuses will be taken away. Since that shouldn't really affect my decision as much as it is, I guess I'd say sure, why not.

**Comment by xsrvmy** [comment]
@kingmathyall I think some people have suggested that the current solver/gold/plat members stand, but an extra tier/title would be added also having 45bld means.

**Comment by lgarron** [comment]
Per #655, we'd like to send this to a Delegate vote.

https://github.com/thewca/worldcubeassociation.org/pull/3640 changes polls on the website to be Delegate-only for now.

@kingmathyall has volunteered to run the poll. How does this sound?
- For transparency, make a (non-sticky? we have lots of sticky posts already) front page post that this poll is happening.
- Set the poll for 1 week.

See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wca-delegates/lhY0MsfN-rw/OGjWHVFaAgAJ for last year's Delegate polling thread.

**Comment by jamesquinn1** [comment]
Do we have results of the delegate poll yet?

**Comment by lgarron** [comment]
> Do we have results of the delegate poll yet?

@kingmathyall, could you post them as soon as it's done?

**Pull request merged**
